/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jackAudio4Java_Server */

#ifndef _Included_jackAudio4Java_Server
#define _Included_jackAudio4Java_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jackAudio4Java_Server
 * Method:    jack_get_version_n
 * Signature: (LjackAudio4Java/types/Int;LjackAudio4Java/types/Int;LjackAudio4Java/types/Int;LjackAudio4Java/types/Int;)V
 */
JNIEXPORT void JNICALL Java_jackAudio4Java_Server_jack_1get_1version_1n
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);


JNIEXPORT int JNICALL test
        (int variable);

#ifdef __cplusplus
}
#endif
#endif
